using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace FlightPlanner
{
    class SplashScreen
    {
        public static void PlaySplash()
        {
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                        ");
            Console.WriteLine(@"                                                                       ");
            Console.WriteLine(@"                                                                       ");
            Console.WriteLine(@"                                                                    ");
            Console.WriteLine(@"                                                                  ");
            Console.WriteLine(@"                                                     ");
            Console.WriteLine(@"                       ________/  \_______      ");
            Console.WriteLine(@"                           o  '\__/  o         ");
            Console.WriteLine(@"                                o o                          ");
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                        ");
            Console.WriteLine(@"                                                                       ");
            Console.WriteLine(@"                                                                       ");
            Console.WriteLine(@"                                                                    ");
            Console.WriteLine(@"                                 I                                 ");
            Console.WriteLine(@"                             -'/.-.\                      ");
            Console.WriteLine(@"                  ____________|  -  |__________      ");
            Console.WriteLine(@"                        O     '\_m_/    O         ");
            Console.WriteLine(@"                              o  o  o                          ");
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                        ");
            Console.WriteLine(@"                                                                       ");
            Console.WriteLine(@"                                                                       ");
            Console.WriteLine(@"                                                                    ");
            Console.WriteLine(@"                               _|_                                 ");
            Console.WriteLine(@"                           ---'.-.'---                       ");
            Console.WriteLine(@"               _______________'  -  '________________      ");
            Console.WriteLine(@"              '' -   --\O/ [^',_m_,' ^] \O/--  -'''     ");
            Console.WriteLine(@"                              O  O  O                          ");
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");
            
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                        ");
            Console.WriteLine(@"                                                                       ");
            Console.WriteLine(@"                                                                       ");
            Console.WriteLine(@"                                   |                                 ");
            Console.WriteLine(@"                                  '__'                                 ");
            Console.WriteLine(@"                            ------'.-.'-----                       ");
            Console.WriteLine(@"            ___________________  '  -  '____________________      ");
            Console.WriteLine(@"          ''' - ---|  --/  \==][^',_m_,' ^][==/  \-- --| -''''     ");
            Console.WriteLine(@"                        \  /   |/   H    \|   \  /                     ");
            Console.WriteLine(@"\\---------------------------- O    OO    O--------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");
            
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                   -'-.                                  ");
            Console.WriteLine(@"                                  ' _ '                                 ");
            Console.WriteLine(@"                        ------- -' .-. '-------                       ");
            Console.WriteLine(@"         ______________________ ' ' - ' '______________________      ");
            Console.WriteLine(@"       ''''' - ---|  --/   \==][^',_m_,' ^][==/   \-- ---| -'''''     ");
            Console.WriteLine(@"                       \   /  ||/   H    \||  \   /                     ");
            Console.WriteLine(@"\\----------------------------OO   O|O    OO--------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");
            
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /  ||/   H    \||  \    /                     ");
            Console.WriteLine(@"\\----------------------------OO   O|O    OO--------------------------------\\ ");
            Console.WriteLine(@" \\--------------------.-----------\\-----------.----------------------------\\");

            Thread.Sleep(400);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /  ||/   H    \||  \    /                     ");
            Console.WriteLine(@"\\---------------------.------OO   O|O    OO---.----------------------------\\ ");
            Console.WriteLine(@" \\---.----------------------------\\-----------------------.----------------\\");

            Thread.Sleep(300);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /  ||/   H    \||  \    /                     ");
            Console.WriteLine(@"\\---.------------------------OO   O|O    OO---------------.----------------\\ ");
            Console.WriteLine(@" \\-------------------.------------\\----------------------------------------\\");

            Thread.Sleep(300);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /  ||/   H    \||  \    /                     ");
            Console.WriteLine(@"                       '--'   OO   O|O    OO   '--'                      ");
            Console.WriteLine(@"\\-------------------.------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\----------.---------------------\\-----------.-------------------.--------\\");

            Thread.Sleep(300);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /  ||/   H    \||  \    /                     ");
            Console.WriteLine(@"                       '--'   OO   O|O    OO   '--'                      ");
            Console.WriteLine();
            Console.WriteLine(@"\\----------.---------------------\\-----------.-------------------.--------\\ ");
            Console.WriteLine(@" \\------------------------------.-\\---------------------.------------------\\");

            Thread.Sleep(300);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /  OO   O|O    OO  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine(@"\\------------------------------.-\\---------------------.------------------\\ ");
            Console.WriteLine(@" \\-------------.------------------\\------.---------------------------------\\");

            Thread.Sleep(300);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /                  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\-------------.------------------\\------.---------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\--------------------------------.-------\\"); 
            
            Thread.Sleep(300);
            Console.Clear();
            Console.WriteLine(@"                                                                         ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /                  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\--------------------------------.-------\\ ");
            Console.WriteLine(@" \\-------------------.------------\\-------------.---.----------------------\\");
            
            Thread.Sleep(300);
            Console.Clear();
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /                  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\-------------------.------------\\-------------.---.----------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\"); 
            
            Thread.Sleep(200);
            Console.Clear();
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /                  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");
            Thread.Sleep(200);
            Console.Clear();
            Console.WriteLine(@"                                    |                                    ");
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /                  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\------------.-------------------\\----------------------------------------\\");
            Thread.Sleep(200);
            Console.Clear();
            Console.WriteLine(@"                                  - '-.                                  ");
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /                  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\------------.-------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\-----------------.--------------\\------.---------------------------------\\");
            Thread.Sleep(150);
            Console.Clear();
            Console.WriteLine(@"                                 ' ___ '                                 ");
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /                  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\-----------------.--------------\\------.---------------------------------\\ ");
            Console.WriteLine(@" \\-----.--------------------------\\---------------.---.--------------------\\");
            
            Thread.Sleep(150);
            Console.Clear();
            Console.WriteLine(@"                     -------- - '  .-.  '-------- -                      ");
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /                  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\-----.--------------------------\\---------------.---.--------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\--.-------------------.-----------------\\");
            
            Thread.Sleep(100);
            Console.Clear();
            Console.WriteLine(@"       ________________________'  ' - '  '_________________________      ");
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /                  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\--.-------------------.-----------------\\ ");
            Console.WriteLine(@" \\--------------.----------------.\\-------------------------------.--------\\");
            Thread.Sleep(100);
            Console.Clear();
            Console.WriteLine(@"     '''''' -| ---| --/    \==][^',_m_,' ^][==/    \--| ---| -''''''     ");
            Console.WriteLine(@"                      \    /                  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------.----------------.\\-------------------------------.--------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");
            
            Thread.Sleep(100);
            Console.Clear();
            Console.WriteLine(@"                      \    /                  \    /                     ");
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\----------.---------------------\\----------------------------------------\\");
            Thread.Sleep(100);
            Console.Clear();
            Console.WriteLine(@"                       '--'                    '--'                      ");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\----------.---------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine();
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");

            Thread.Sleep(50);
            Console.Clear();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine(@"█████████████████████▀█████████████████████████████████████████████████████████");
            Console.WriteLine(@"█▄─▄▄─█▄─▄███▄─▄█─▄▄▄▄█─█─█─▄─▄─█▄─▄▄─█▄─▄████▀▄─██▄─▀█▄─▄█▄─▀█▄─▄█▄─▄▄─█▄─▄▄▀█");
            Console.WriteLine(@"██─▄████─██▀██─██─██▄─█─▄─███─████─▄▄▄██─██▀██─▀─███─█▄▀─███─█▄▀─███─▄█▀██─▄─▄█");
            Console.WriteLine(@"▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▀▄▀▀▄▄▄▀▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▀▀▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀");
            Console.WriteLine(@"\\--------------------------------\\----------------------------------------\\ ");
            Console.WriteLine(@" \\--------------------------------\\----------------------------------------\\");
            Console.WriteLine();
            Console.WriteLine("                     Lets discover the world together!");
            Console.WriteLine("                           PRESS ENTER TO START");
            
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.ReadLine();

        }

    }
}
